version: '3'
services:
  app:
    container_name: prolectron5
    restart: always
    build: .
    ports:
      - '80:3001'
    links:
      - mongo
  mongo:
    container_name: shop
    image: shop
    ports:
      - '27017:27017'
