# Generated by Django 4.1.2 on 2022-10-27 00:28

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(default=-1, primary_key=True, serialize=False, verbose_name='id категории')),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id категории')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=150, verbose_name='Наименование товара')),
                ('images', models.ImageField(upload_to='media')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('discription', models.TextField(max_length=2000, verbose_name='Описание')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('provider_email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id тега')),
                ('name', models.CharField(max_length=150, verbose_name='Название тега')),
                ('slug', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='SuppliedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_for_product', models.IntegerField(verbose_name='Цена за 1 единицу товара')),
                ('products_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product', verbose_name='id товаров')),
                ('provider_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='id поставщика')),
            ],
            options={
                'verbose_name': 'Поставляемый товар',
                'verbose_name_plural': 'Поставляемые товары',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tag'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('order_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id заказа')),
                ('created_at', models.DateTimeField(verbose_name='Дата когда был создан заказ')),
                ('status', models.TextField(choices=[('AWCO', 'awaiting_confirmation'), ('PERF', 'performed'), ('COMP', 'completed')])),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product', verbose_name='id товаров')),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='id покупателя')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField(max_length=200, verbose_name='Адрес')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('favourites', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favourites', to='main.product', verbose_name='Избранное')),
                ('shopping_cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_cart', to='main.product', verbose_name='Корзина покупок')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField(default='NULL', primary_key=True, serialize=False, verbose_name='id комментария')),
                ('created_at', models.DateField(default='NULL', verbose_name='Дата создания комментария')),
                ('created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем создан комментарий')),
                ('product_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.product', verbose_name='К какому товару относится комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
